import { ComponentData } from '@/components/page-editor/types'

const mockComponentDataList: ComponentData[] = [
  {
    'showName': '按钮-重置',
    'componentName': 'BButton',
    'id': 'BButton-nz6dteey',
    'setting': {
      'text': '重置',
      'type': 'default',
      'controlHidden': false,
      'danger': false,
      'disabled': false,
    },
    'width': 76,
    'height': 46,
    'left': 0,
    'top': 92,
  },
  {
    'showName': '按钮-查询',
    'componentName': 'BButton',
    'id': 'BButton-9yjy7o5m',
    'setting': {
      'text': '查询',
      'type': 'primary',
      'controlHidden': false,
      'danger': false,
      'disabled': false,
    },
    'width': 152,
    'height': 46,
    'left': 76,
    'top': 92,
  },
  {
    'showName': '输入-查询 UIN',
    'componentName': 'BInput',
    'id': 'BInput-4ilyo7eq',
    'setting': {
      'label': 'UIN',
      'name': 'uin',
      'value': null,
      'extra': '',
      'placeholder': '请输入...',
      'controlHidden': false,
      'allowClear': true,
      'disabled': false,
    },
    'width': 228,
    'height': 92,
    'left': 0,
    'top': 0,
  },
  {
    'showName': 'A触发B',
    'componentName': 'BNo111',
    'id': 'BNo111-4ilyo7eq',
    'setting': {},
    'width': 76,
    'height': 46,
    'left': 228,
    'top': 0,
  },
  {
    'showName': '按钮-测试被修改',
    'componentName': 'BButton',
    'id': 'BButton-ieb6r3n2',
    'setting': {
      'text': '测试被修改',
      'type': 'primary',
      'controlHidden': false,
      'danger': false,
      'disabled': false,
    },
    'width': 114,
    'height': 46,
    'left': 0,
    'top': 276,
  },
  {
    'showName': '按钮-设置为禁用',
    'componentName': 'BButton',
    'id': 'BButton-fv83mzvt',
    'setting': {
      'text': '设置为禁用',
      'type': 'primary',
      'controlHidden': false,
      'danger': false,
      'disabled': false,
    },
    'width': 114,
    'height': 46,
    'left': 0,
    'top': 207,
  },
  {
    'showName': '延迟-重置按钮',
    'componentName': 'BTimeout',
    'id': 'BTimeout-p50w64tc',
    'setting': {
      'time': 2000,
    },
    'width': 0,
    'height': 0,
    'left': 0,
    'top': 368,
  },
  {
    'showName': '定时-执行',
    'componentName': 'BInterval',
    'id': 'BInterval-knaw34ub',
    'setting': {
      'time': 2000,
    },
    'width': 0,
    'height': 0,
    'left': 76,
    'top': 368,
  },
]

export default mockComponentDataList
